name: Update BunnyCDN IPSet

on:
  workflow_dispatch: # Trigger manually
  schedule:
    - cron: "0 0 * * *" # Run daily

jobs:
  update-ipset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ipset jq

    - name: Fetch BunnyCDN IPs
      run: |
        # Fetch IPv4 and IPv6 IP lists
        curl -s https://bunnycdn.com/api/system/edgeserverlist -H "Accept: application/json" | jq -r .[] > bunny_ipv4.txt
        curl -s https://bunnycdn.com/api/system/edgeserverlist/ipv6 -H "Accept: application/json" | jq -r .[] > bunny_ipv6.txt

    - name: Validate and Remove Duplicates from IP Files
      run: |
        # Validate and clean IPv4
        grep -E '^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.([0-9]{1,3}\.){2}[0-9]{1,3}$' bunny_ipv4.txt | sort -u > clean_ipv4.txt
        mv clean_ipv4.txt bunny_ipv4.txt

        # Validate and clean IPv6
        grep -E '^([a-fA-F0-9:]+:+)+[a-fA-F0-9]+$' bunny_ipv6.txt | sort -u > clean_ipv6.txt
        mv clean_ipv6.txt bunny_ipv6.txt

    - name: Commit and Push IP Files
      run: |
        git config user.name "vCoDMods"
        git config user.email "admin@vcodmods.com"

        # Add and commit the IP files
        git add bunny_ipv4.txt bunny_ipv6.txt
        git commit -m "Update BunnyCDN EdgeServer IPs"
        git push
